import type { Metadata } from "next";
import {
  ClerkProvider,
  RedirectToSignIn,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConversationProvider } from "@/hooks/useConversation";
import { TooltipProvider } from "@/components/ui/tooltip";
import ConvexClientProvider from "@/components/provider/ConvexClientProvider";
import Home from "./page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en">
      <body>
        <ClerkProvider>
          <ConvexClientProvider>
            <ConversationProvider>
              {children}
              <Home />
            </ConversationProvider>
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}


